// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tiqnfldnraknzegtfqha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpcW5mbGRucmFrbnplZ3RmcWhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MzAzMjEsImV4cCI6MjA2NTIwNjMyMX0.81pz7JQquZaXk5dqMz2LjgHDkq-kyQX3swaQCsEl5bo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);